
package default_package;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-12-28T16:45:54.640Z
 * Generated source version: 3.6.2
 *
 */
public final class MathUtility_MathUtilityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://default_package/", "MathUtilityService");

    private MathUtility_MathUtilityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MathUtilityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MathUtilityService ss = new MathUtilityService(wsdlURL, SERVICE_NAME);
        MathUtility port = ss.getMathUtilityPort();

        {
        System.out.println("Invoking validaPraia...");
        java.lang.String _validaPraia_arg0 = "_validaPraia_arg0-707166506";
        java.util.List<java.lang.Object> _validaPraia__return = port.validaPraia(_validaPraia_arg0);
        System.out.println("validaPraia.result=" + _validaPraia__return);


        }
        {
        System.out.println("Invoking funcCancelar...");
        java.lang.String _funcCancelar_arg0 = "_funcCancelar_arg0-1012115644";
        int _funcCancelar_arg1 = 1797569654;
        java.lang.String _funcCancelar_arg2 = "_funcCancelar_arg2-688408687";
        java.util.List<java.lang.Object> _funcCancelar__return = port.funcCancelar(_funcCancelar_arg0, _funcCancelar_arg1, _funcCancelar_arg2);
        System.out.println("funcCancelar.result=" + _funcCancelar__return);


        }
        {
        System.out.println("Invoking validaHora...");
        java.lang.String _validaHora_arg0 = "_validaHora_arg0-2090614411";
        java.util.List<java.lang.Object> _validaHora__return = port.validaHora(_validaHora_arg0);
        System.out.println("validaHora.result=" + _validaHora__return);


        }
        {
        System.out.println("Invoking funcReservar...");
        java.lang.String _funcReservar_arg0 = "_funcReservar_arg0-1505280088";
        int _funcReservar_arg1 = -1508519244;
        java.lang.String _funcReservar_arg2 = "_funcReservar_arg2320397729";
        int _funcReservar_arg3 = 1394080476;
        java.util.List<java.lang.Object> _funcReservar__return = port.funcReservar(_funcReservar_arg0, _funcReservar_arg1, _funcReservar_arg2, _funcReservar_arg3);
        System.out.println("funcReservar.result=" + _funcReservar__return);


        }
        {
        System.out.println("Invoking funcListar...");
        java.lang.String _funcListar_arg0 = "_funcListar_arg01311245016";
        int _funcListar_arg1 = 1761120085;
        java.lang.String _funcListar_arg2 = "_funcListar_arg2487094697";
        java.util.List<java.lang.Object> _funcListar__return = port.funcListar(_funcListar_arg0, _funcListar_arg1, _funcListar_arg2);
        System.out.println("funcListar.result=" + _funcListar__return);


        }
        {
        System.out.println("Invoking validaNum...");
        java.lang.String _validaNum_arg0 = "_validaNum_arg0-1811503983";
        java.util.List<java.lang.Object> _validaNum__return = port.validaNum(_validaNum_arg0);
        System.out.println("validaNum.result=" + _validaNum__return);


        }

        System.exit(0);
    }

}
