package default_package;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-12-28T16:45:54.825Z
 * Generated source version: 3.6.2
 *
 */
@WebService(targetNamespace = "http://default_package/", name = "MathUtility")
@XmlSeeAlso({ObjectFactory.class})
public interface MathUtility {

    @WebMethod(operationName = "valida_praia")
    @RequestWrapper(localName = "valida_praia", targetNamespace = "http://default_package/", className = "default_package.ValidaPraia")
    @ResponseWrapper(localName = "valida_praiaResponse", targetNamespace = "http://default_package/", className = "default_package.ValidaPraiaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> validaPraia(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "funcCancelar", targetNamespace = "http://default_package/", className = "default_package.FuncCancelar")
    @ResponseWrapper(localName = "funcCancelarResponse", targetNamespace = "http://default_package/", className = "default_package.FuncCancelarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> funcCancelar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod(operationName = "valida_hora")
    @RequestWrapper(localName = "valida_hora", targetNamespace = "http://default_package/", className = "default_package.ValidaHora")
    @ResponseWrapper(localName = "valida_horaResponse", targetNamespace = "http://default_package/", className = "default_package.ValidaHoraResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> validaHora(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "funcReservar", targetNamespace = "http://default_package/", className = "default_package.FuncReservar")
    @ResponseWrapper(localName = "funcReservarResponse", targetNamespace = "http://default_package/", className = "default_package.FuncReservarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> funcReservar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @WebMethod
    @RequestWrapper(localName = "funcListar", targetNamespace = "http://default_package/", className = "default_package.FuncListar")
    @ResponseWrapper(localName = "funcListarResponse", targetNamespace = "http://default_package/", className = "default_package.FuncListarResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> funcListar(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod(operationName = "valida_num")
    @RequestWrapper(localName = "valida_num", targetNamespace = "http://default_package/", className = "default_package.ValidaNum")
    @ResponseWrapper(localName = "valida_numResponse", targetNamespace = "http://default_package/", className = "default_package.ValidaNumResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<java.lang.Object> validaNum(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
