
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package default_package;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.6.2
 * 2023-12-28T16:45:54.798Z
 * Generated source version: 3.6.2
 *
 */

@javax.jws.WebService(
                      serviceName = "MathUtilityService",
                      portName = "MathUtilityPort",
                      targetNamespace = "http://default_package/",
                      wsdlLocation = "http://127.0.0.1:8080/proj2/services/MathUtilityPort?wsdl",
                      endpointInterface = "default_package.MathUtility")

public class MathUtilityPortImpl implements MathUtility {

    private static final Logger LOG = Logger.getLogger(MathUtilityPortImpl.class.getName());

    /* (non-Javadoc)
     * @see default_package.MathUtility#validaPraia(java.lang.String arg0)*
     */
    public java.util.List<java.lang.Object> validaPraia(java.lang.String arg0) {
        LOG.info("Executing operation validaPraia");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#funcCancelar(java.lang.String arg0, int arg1, java.lang.String arg2)*
     */
    public java.util.List<java.lang.Object> funcCancelar(java.lang.String arg0, int arg1, java.lang.String arg2) {
        LOG.info("Executing operation funcCancelar");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#validaHora(java.lang.String arg0)*
     */
    public java.util.List<java.lang.Object> validaHora(java.lang.String arg0) {
        LOG.info("Executing operation validaHora");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#funcReservar(java.lang.String arg0, int arg1, java.lang.String arg2, int arg3)*
     */
    public java.util.List<java.lang.Object> funcReservar(java.lang.String arg0, int arg1, java.lang.String arg2, int arg3) {
        LOG.info("Executing operation funcReservar");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        System.out.println(arg3);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#funcListar(java.lang.String arg0, int arg1, java.lang.String arg2)*
     */
    public java.util.List<java.lang.Object> funcListar(java.lang.String arg0, int arg1, java.lang.String arg2) {
        LOG.info("Executing operation funcListar");
        System.out.println(arg0);
        System.out.println(arg1);
        System.out.println(arg2);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see default_package.MathUtility#validaNum(java.lang.String arg0)*
     */
    public java.util.List<java.lang.Object> validaNum(java.lang.String arg0) {
        LOG.info("Executing operation validaNum");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.Object> _return = new java.util.ArrayList<java.lang.Object>();
            java.lang.Object _returnVal1 = null;
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
